services:
  postgres:
    image: postgres:16
    container_name: lead_intelligence_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: lead_intelligence
      POSTGRES_USER: lead_admin
      POSTGRES_PASSWORD: lead_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: